"""End-to-end tests for the `/ci` PR-comment dispatcher (ci/gh_command.py).

Drives the real dispatch path — comment parsing, job-spec construction, pod
env assembly, PR feedback, commit statuses — with the RunPod and GitHub
layers mocked out, asserting exactly which pods and comments would be
created. The only untested seam left is the live RunPod/GitHub APIs, which
the first real `/ci` comment exercises after merge.
"""

import base64
import json
from types import SimpleNamespace

import pytest

from ci import gh_command

SHA = "0123456789abcdef0123456789abcdef01234567"
FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"


@pytest.fixture
def gh_ctx(monkeypatch):
    """Env + mocks for a /ci comment on PR #42; returns the capture dict."""
    captured = {"pods": [], "comments": [], "statuses": [], "edits": []}

    monkeypatch.setenv("PR_NUMBER", "42")
    monkeypatch.setenv("HEAD_SHA", SHA)
    monkeypatch.setenv(
        "COMMENT_URL", "https://github.com/beyarkay/factorion/pull/42#issuecomment-999"
    )
    monkeypatch.setenv("RUNPOD_API_KEY", "rp-test")
    monkeypatch.setenv("WANDB_API_KEY", "wb-test")
    monkeypatch.setenv("GITHUB_TOKEN", "gh-test")
    monkeypatch.setenv("GITHUB_REPOSITORY", "beyarkay/factorion")

    def fake_create_pod(name, gpu_type, docker_args, env):
        captured["pods"].append(
            {"name": name, "gpu_type": gpu_type, "docker_args": docker_args, "env": env}
        )
        return {"id": f"pod-{len(captured['pods'])}"}

    monkeypatch.setattr("ci.runpod_api.create_pod", fake_create_pod)
    monkeypatch.setattr(gh_command, "_wandb_entity", lambda: "testent")
    monkeypatch.setattr(gh_command, "_missing_run_warnings", lambda infos: "")
    # Live pod/run statuses hit RunPod + W&B; give every pod a "running" pair.
    monkeypatch.setattr(
        gh_command,
        "_launch_statuses",
        lambda infos: {i["pod_id"]: ("🚀", "🚀") for i in infos},
    )

    def fake_post_comment(pr, body):
        captured["comments"].append((pr, body))
        return 9000 + len(captured["comments"])  # a comment id, like the real API

    monkeypatch.setattr(gh_command.github_api, "post_pr_comment", fake_post_comment)
    monkeypatch.setattr(
        gh_command.github_api,
        "update_pr_comment",
        lambda comment_id, body: captured["edits"].append((comment_id, body)),
    )
    monkeypatch.setattr(
        gh_command.github_api,
        "set_commit_status",
        lambda sha, state, context, description: captured["statuses"].append(
            (sha, state, context, description)
        ),
    )
    return captured


def _job_spec(pod):
    return json.loads(base64.b64decode(pod["env"]["FCI_JOB_B64"]))


def _stub_sweep(monkeypatch, config):
    """Patch the git + W&B seams a `/ci sweep` touches, with `config` standing
    in for the sweep yaml at the commit."""
    monkeypatch.setattr(gh_command, "read_sweep_config", lambda algo, sha: config)
    monkeypatch.setattr(
        gh_command, "create_sweep", lambda algo, sha: f"me/factorion/swp-{algo}"
    )
    monkeypatch.setattr(gh_command, "_wait_for_sweep", lambda path: None)
    monkeypatch.setattr("ci.report.sweep_report", lambda path: "SWEEP-MD")


class TestSftDispatch:
    def test_launches_one_pod_and_comments(self, gh_ctx, monkeypatch):
        monkeypatch.setenv("COMMENT_BODY", "/ci sft --num-samples 200000")
        gh_command.main()

        (pod,) = gh_ctx["pods"]
        spec = _job_spec(pod)
        assert spec["kind"] == "sft"
        assert spec["sha"] == SHA
        assert spec["num_samples"] == 200000
        assert "pr:42" in spec["extra_tags"]
        # The pod gets the secrets + the pinned commit to clone.
        assert pod["env"]["WANDB_API_KEY"] == "wb-test"
        assert pod["env"]["FCI_SHA"] == SHA
        assert pod["name"].startswith("factorion-ci-sft-")

        # A boot failure (pod dies before jobs.py) still reports to the PR:
        # the pod carries the kind + pr tags the reporter cron keys on, and
        # the bootstrap fetches the exact SHA so a vanished branch tip (merged
        # + deleted PR branch, or force-push) still checks out.
        assert pod["env"]["FCI_KIND"] == "sft"
        assert "pr:42" in json.loads(base64.b64decode(pod["env"]["FCI_EXTRA_TAGS_B64"]))
        boot = base64.b64decode(pod["env"]["FCI_BOOT_B64"]).decode()
        assert 'git fetch --quiet origin "${FCI_SHA}"' in boot
        assert "boot-failure" in boot and "FCI_EXTRA_TAGS_B64" in boot

        ((pr, body),) = gh_ctx["comments"]
        assert pr == 42
        assert "pod-1" in body
        # The W&B run id is minted at launch and linked in the comment.
        run_id = pod["env"]["FCI_WANDB_RUN_ID"]
        assert len(run_id) == 8
        assert f"https://wandb.ai/testent/factorion/runs/{run_id}" in body
        assert "https://console.runpod.io/pods?id=pod-1" in body
        # Every CI comment links back to the /ci comment that triggered it.
        assert "Originally triggered by" in body
        assert "#issuecomment-999" in body


class TestPpoDispatch:
    def test_ppo_carries_checkpoint(self, gh_ctx, monkeypatch):
        monkeypatch.setenv("COMMENT_BODY", "/ci ppo --start-from j0s5y2mc")
        gh_command.main()

        (pod,) = gh_ctx["pods"]
        spec = _job_spec(pod)
        assert spec["kind"] == "ppo"
        assert spec["start_from"] == "j0s5y2mc"
        assert spec["total_timesteps"] is None  # PpoArgs default applies


class TestCompareDispatch:
    def test_fans_out_pods_waits_and_gates(self, gh_ctx, monkeypatch):
        monkeypatch.setenv(
            "COMMENT_BODY",
            "/ci compare --seeds 2 --num-samples 1000\n"
            "assert pr:val/thput > main:val/thput\n",
        )
        # Base ref resolution + the W&B-touching steps are stubbed out.
        monkeypatch.setattr(gh_command, "resolve_ref", lambda ref: "b" * 40)
        waits = []
        monkeypatch.setattr(
            "ci.report.wait_for_groups", lambda **kw: waits.append(kw)
        )
        reports = []

        def fake_compare_report(main_group, pr_group, assertions=None):
            reports.append((main_group, pr_group, assertions))
            return "REPORT-MD", True

        monkeypatch.setattr("ci.report.compare_report", fake_compare_report)

        gh_command.main()

        # One pod per side (2 total), each running both seeds sequentially;
        # sides split across the two shas.
        assert len(gh_ctx["pods"]) == 2
        shas = [_job_spec(p)["sha"] for p in gh_ctx["pods"]]
        assert shas.count(SHA) == 1 and shas.count("b" * 40) == 1
        # Each pod carries the full seed list to run in turn.
        assert all(_job_spec(p)["seeds"] == [1, 2] for p in gh_ctx["pods"])

        # Waited for both groups (still 2 finished runs each), then reported.
        assert waits[0]["expect_each"] == 2
        assert reports[0][2] == ["pr:val/thput > main:val/thput"]

        # The launch comment starts all-pending and is edited in place with
        # live pod statuses (final refresh after the wait ends). Each pod line
        # shows one emoji (compare pods have no pre-minted W&B run to link);
        # the +1 is the status legend line, which mentions every state once.
        launch_body = gh_ctx["comments"][0][1]
        assert launch_body.count("⏳") == len(gh_ctx["pods"]) + 1
        ((edit_id, edit_body),) = gh_ctx["edits"]
        assert edit_id == 9001  # edits target the launch comment, not a new one
        assert edit_body.count("🚀") == len(gh_ctx["pods"]) + 1

        # Status: pending at launch, success after the passing report.
        states = [s[1] for s in gh_ctx["statuses"]]
        assert states == ["pending", "success"]
        assert any("REPORT-MD" in body for _, body in gh_ctx["comments"])

    def test_failed_assertion_fails_the_check(self, gh_ctx, monkeypatch):
        monkeypatch.setenv(
            "COMMENT_BODY", "/ci compare --seeds 1\nassert pr:val/acc > 1000"
        )
        monkeypatch.setattr(gh_command, "resolve_ref", lambda ref: "b" * 40)
        monkeypatch.setattr("ci.report.wait_for_groups", lambda **kw: None)
        monkeypatch.setattr(
            "ci.report.compare_report",
            lambda main_group, pr_group, assertions=None: ("BAD-MD", False),
        )
        with pytest.raises(SystemExit) as exc:
            gh_command.main()
        assert exc.value.code == 1
        assert [s[1] for s in gh_ctx["statuses"]] == ["pending", "failure"]

    def test_render_deps_probe_never_imports_here(self, monkeypatch):
        """The probe must run in a CHILD process: importing factorion_rs in
        this one binds the repo's source directory (a namespace package with
        no compiled symbols) into sys.modules, where it shadows the wheel the
        install then builds — observed live on PR #383."""
        import subprocess

        calls = []

        def fake_run(cmd, **kw):
            calls.append(cmd)
            return SimpleNamespace(returncode=0)

        monkeypatch.setattr(subprocess, "run", fake_run)
        gh_command._ensure_render_deps()
        ((probe,),) = [(c,) for c in calls]  # exactly one call: the probe
        assert probe[1] == "-c" and "import torch" in probe[2]

    def test_render_deps_install_when_missing(self, monkeypatch):
        import subprocess

        calls = []

        def fake_run(cmd, **kw):
            calls.append(cmd)
            return SimpleNamespace(returncode=len(calls) == 1)  # probe fails

        monkeypatch.setattr(subprocess, "run", fake_run)
        gh_command._ensure_render_deps()
        assert any("torch" in c and "--index-url" in c for c in calls[1:])
        assert any(c[:2] == ["maturin", "build"] for c in calls[1:])

    def _stub_compare(self, monkeypatch, ok=True):
        monkeypatch.setattr(gh_command, "resolve_ref", lambda ref: "b" * 40)
        monkeypatch.setattr("ci.report.wait_for_groups", lambda **kw: None)
        monkeypatch.setattr(
            "ci.report.compare_report",
            lambda main_group, pr_group, assertions=None: ("REPORT-MD", ok),
        )

    def test_factory_renders_follow_the_metric_report(self, gh_ctx, monkeypatch):
        monkeypatch.setenv("COMMENT_BODY", "/ci compare --seeds 1")
        self._stub_compare(monkeypatch)
        monkeypatch.setattr(
            "ci.report.compare_renders",
            lambda main_group, pr_group: f"RENDERS-MD {pr_group} {main_group}",
        )
        gh_command.main()

        bodies = [body for _, body in gh_ctx["comments"]]
        report_i = next(i for i, b in enumerate(bodies) if "REPORT-MD" in b)
        renders_i = next(i for i, b in enumerate(bodies) if "RENDERS-MD" in b)
        assert report_i < renders_i, "numbers first, then the qualitative diff"
        assert "-pr" in bodies[renders_i] and "-main" in bodies[renders_i]

    def test_render_failure_never_sinks_the_compare(self, gh_ctx, monkeypatch):
        """Hours of GPU time hang on this report — a rendering bug must not
        cost the metric report or the commit status."""
        monkeypatch.setenv("COMMENT_BODY", "/ci compare --seeds 1")
        self._stub_compare(monkeypatch)

        def boom(main_group, pr_group):
            raise RuntimeError("no checkpoint artifact")

        monkeypatch.setattr("ci.report.compare_renders", boom)
        gh_command.main()

        assert any("REPORT-MD" in body for _, body in gh_ctx["comments"])
        assert [s[1] for s in gh_ctx["statuses"]] == ["pending", "success"]

    def test_launch_comment_echoes_job_spec(self, gh_ctx, monkeypatch):
        monkeypatch.setenv("COMMENT_BODY", "/ci sft --num-samples 200000")
        gh_command.main()
        ((_, body),) = gh_ctx["comments"]
        assert '"num_samples": 200000' in body  # params visible up front
        assert "training_config.py" in body


class TestComparePpoDispatch:
    def test_positional_algo_ppo(self, gh_ctx, monkeypatch):
        monkeypatch.setenv(
            "COMMENT_BODY", "/ci compare ppo --start-from j0s5y2mc --seeds 1"
        )
        monkeypatch.setattr(gh_command, "resolve_ref", lambda ref: "b" * 40)
        monkeypatch.setattr("ci.report.wait_for_groups", lambda **kw: None)
        monkeypatch.setattr(
            "ci.report.compare_report",
            lambda main_group, pr_group, assertions=None: ("MD", True),
        )
        gh_command.main()

        assert len(gh_ctx["pods"]) == 2  # one pod per side
        specs = [_job_spec(p) for p in gh_ctx["pods"]]
        assert {s["kind"] for s in specs} == {"compare"}
        assert {s["algo"] for s in specs} == {"ppo"}
        assert {s["start_from"] for s in specs} == {"j0s5y2mc"}
        assert all(s["seeds"] == [1] for s in specs)


class TestSweepDispatch:
    def test_positional_algo_sft(self, gh_ctx, monkeypatch):
        monkeypatch.setenv("COMMENT_BODY", "/ci sweep sft --pods 2")
        _stub_sweep(
            monkeypatch,
            {
                "metric": {"name": "val/acc", "goal": "maximize"},
                "run_cap": 30,
                "parameters": {"lr": {}, "batch_size": {}},
            },
        )
        gh_command.main()

        assert len(gh_ctx["pods"]) == 2
        specs = [_job_spec(p) for p in gh_ctx["pods"]]
        assert {s["kind"] for s in specs} == {"sweep"}
        assert {s["sweep_path"] for s in specs} == {"me/factorion/swp-sft"}
        # Sweep pods carry the pr tag too, so a pod that dies before its agents
        # start still reports the boot failure to the PR via the reporter cron.
        for pod in gh_ctx["pods"]:
            assert "pr:42" in json.loads(base64.b64decode(pod["env"]["FCI_EXTRA_TAGS_B64"]))
            assert pod["env"]["FCI_KIND"] == "sweep"
        # The launch comment shows what's being swept, not just pod ids.
        launch_body = gh_ctx["comments"][0][1]
        assert "val/acc" in launch_body and "run_cap 30" in launch_body
        assert any("SWEEP-MD" in body for _, body in gh_ctx["comments"])

    def test_sweep_requires_algo(self, gh_ctx, monkeypatch):
        monkeypatch.setenv("COMMENT_BODY", "/ci sweep")
        with pytest.raises(SystemExit):
            gh_command.main()
        assert gh_ctx["pods"] == []


class TestClaudeAuthoredLimits:
    """A /ci comment signed by Claude Code is capped to the ci/config.py
    CLAUDE_MAX_*; the same command typed by a human is not."""

    @pytest.mark.parametrize(
        "command,field,capped,uncapped",
        [
            ("/ci sft --num-samples 40000000", "num_samples", 5_000_000, 40000000),
            # Unset is the expensive case: SftArgs' default is 45M samples.
            ("/ci sft", "num_samples", 5_000_000, None),
            ("/ci sft --num-samples 200000", "num_samples", 200000, 200000),
            (
                "/ci ppo --start-from j0s5y2mc --total-timesteps 40000000",
                "total_timesteps",
                5_000_000,
                40000000,
            ),
        ],
    )
    def test_cost_knobs(self, gh_ctx, monkeypatch, command, field, capped, uncapped):
        monkeypatch.setenv("COMMENT_BODY", command + FOOTER)
        gh_command.main()
        assert _job_spec(gh_ctx["pods"][0])[field] == capped

        gh_ctx["pods"].clear()
        monkeypatch.setenv("COMMENT_BODY", command)
        gh_command.main()
        assert _job_spec(gh_ctx["pods"][0])[field] == uncapped

    @pytest.mark.parametrize(
        "trailer,footered",
        [
            (FOOTER, True),
            ("\U0001f916 Generated with [Claude Code](https://claude.com/claude-code)", True),
            # Real comment bodies off PR #365 — a human's own command, their
            # prose, and the dispatcher's own comments (which the reporter cron
            # re-reads). None may trip the footer check.
            ("", False),
            ("Soo this is a bugfix, and it mostly performs worse", False),
            ("_Originally triggered by [this comment](https://github.com/x)_", False),
            ("| `rollout/thput` | 0.7746 | 0.6565 | -0.1181 | 0.121 |", False),
        ],
    )
    def test_footer_detection(self, gh_ctx, monkeypatch, trailer, footered):
        monkeypatch.setenv("COMMENT_BODY", "/ci sft --num-samples 40000000\n" + trailer)
        gh_command.main()
        expected = 5_000_000 if footered else 40000000
        assert _job_spec(gh_ctx["pods"][0])["num_samples"] == expected

    def test_compare_seeds_and_timesteps(self, gh_ctx, monkeypatch):
        monkeypatch.setenv(
            "COMMENT_BODY",
            "/ci compare ppo --start-from j0s5y2mc --seeds 8 "
            "--total-timesteps 10000000" + FOOTER,
        )
        monkeypatch.setattr(gh_command, "resolve_ref", lambda ref: "b" * 40)
        monkeypatch.setattr("ci.report.wait_for_groups", lambda **kw: None)
        monkeypatch.setattr(
            "ci.report.compare_report",
            lambda main_group, pr_group, assertions=None: ("MD", True),
        )
        gh_command.main()

        specs = [_job_spec(p) for p in gh_ctx["pods"]]
        assert all(s["seeds"] == [1, 2, 3] for s in specs)
        assert all(s["total_timesteps"] == 5_000_000 for s in specs)

    @pytest.mark.parametrize(
        "run_cap,footer,launches",
        [(80, FOOTER, False), (None, FOOTER, False), (10, FOOTER, True), (80, "", True)],
    )
    def test_sweep_run_cap(self, gh_ctx, monkeypatch, run_cap, footer, launches):
        monkeypatch.setenv("COMMENT_BODY", "/ci sweep sft" + footer)
        _stub_sweep(monkeypatch, {"run_cap": run_cap, "metric": {}, "parameters": {}})
        if launches:
            gh_command.main()
        else:
            with pytest.raises(SystemExit) as exc:
                gh_command.main()
            assert exc.value.code == 1
            assert "sweep refused" in gh_ctx["comments"][0][1]
        # Refusal lands before the sweep is created, so nothing was launched.
        assert len(gh_ctx["pods"]) == int(launches)


class TestBadInput:
    def test_unparseable_command_posts_usage(self, gh_ctx, monkeypatch):
        monkeypatch.setenv("COMMENT_BODY", "/ci frobnicate --hard")
        with pytest.raises(SystemExit):
            gh_command.main()
        ((_, body),) = gh_ctx["comments"]
        assert "could not parse" in body
        assert gh_ctx["pods"] == []

    def test_help_covers_every_command_with_examples(self, gh_ctx, monkeypatch):
        monkeypatch.setenv("COMMENT_BODY", "/ci help")
        gh_command.main()
        ((_, body),) = gh_ctx["comments"]
        for snippet in (
            "/ci sft --num-samples 5000000",  # concrete example, not just grammar
            "/ci ppo --start-from",
            "/ci compare sft",
            "/ci compare ppo --start-from",
            "assert pr:val/thput > main:val/thput",
            "/ci sweep sft",
            "/ci pods",
            "/ci kill",
            "/ci watchdog",
        ):
            assert snippet in body, f"help is missing {snippet!r}"
        assert gh_ctx["pods"] == []
